max_wav_value = 32768
filter_length = 2048
win_length = 2048
n_mel_channels = 128

sampling_rate = 40000
hop_length = 400
write_mute = true
slice = true
f0_max = 1100.0
f0_min = 50.0
f0_mel_min = 0.0

[[subsets]]
data_dir = "./datasets/template"
